### ISSUE TITLE
 사전검색이 계속 오류납니다.

### ISSUE THREAD

**Issue by LYC2737** [Kuniz/alfnaversearch#27]
평소 열심히 사전 검색을 애용했는데 최근 갑자기 아래와 같이 오류가 나서 게시글 남겨놓습니다.
<img width="683" alt="image" src="https://github.com/Kuniz/alfnaversearch/assets/75245950/18d0edb8-69a7-4896-8af5-d959f1bb8711">

**Comment by Kuniz** [comment]
안녕하세요.

해당메시지로는 정확한 상황을 확인하기 어려워서요. 최신 버전으로 설치를 해주시구요. 그래도 안되면, macOS 버전, alfred 버전, 어떤 입력을 했는데 에러를 발생했는지 알려주시면 확인해보겠습니다 ~ 기본적으로는 macOS의 최신버전을 따라고 있어서, 상황에 따라서는 그쪽에서 문제가 있을 수도 있습니다.

감사합니다.

**Comment by LYC2737** [comment]
알프레드는 5.5ver
맥북도 최신업데이트 완료된 상황입니다

**Comment by LYC2737** [comment]
네이버 서치는 정상적으로 작동됩니다.
사전들의 경우는 url 문제라 계속 뜹니다

**Comment by Kuniz** [comment]
https://github.com/Kuniz/alfnaversearch/releases/download/v0.3.2/NaverSearch.alfredworkflow

최신 워크플로우도 안된다는 말씀이신가요?

**Comment by LYC2737** [comment]
옙!!! 재설치 여러번 했지만 해결되지 않습니다.

**Comment by onestn** [comment]
I have the same problem.

The version I used is as follows:
- macos: Sonoma 14.4.1
- alfred: 5.5

**Comment by Kuniz** [comment]
새로 업데이트된 v0.3.3 으로 확인 부탁드려요!

**Comment by onestn** [comment]
정상적으로 동작하는 것을 확인하였습니다.
빠른 수정 감사합니다!

**Comment by ksseono** [comment]
안녕하세요. 저도 동일한 에러가 발생하고 있습니다. 일반검색, 지도검색 등은 이슈가 없으나 유독 사전검색에서만 오류가 발생합니다.

- 디바이스: Apple M3 Pro
- OS: macOS Sonoma version 14.6 (23G80)
- Alfred version: 5.6 [2290]
- alfnaversearch version: v0.3.5

Alfred 디버깅모드에서의 로그 첨부합니다. 

```
[13:49:47.181] Naver Search[Script Filter] Queuing argument 't'
[13:49:47.314] Naver Search[Script Filter] Script with argv '(null)' finished
[13:49:47.318] ERROR: Naver Search[Script Filter] Code 1: .
13:49:47 workflow.py:2482 DEBUG    ---------- Naver Search (0.3.5) ----------
13:49:47 workflow.py:2502 ERROR    <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1028)>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              encode_chunked=req.has_header('Transfer-encoding'))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1338, in request
    self._send_request(method, url, body, headers, encode_chunked)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1384, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1333, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1093, in _send_output
    self.send(msg)
    ~~~~~~~~~^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1037, in send
    self.connect()
    ~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1479, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
                                          server_hostname=server_hostname)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1028)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ksseono/Alfred.alfredpreferences/workflows/user.workflow.6543A76E-F5BF-4FB8-A158-DC8216A84E31/workflow/workflow.py", line 2495, in run
    func(self)
    ~~~~^^^^^^
  File "/Users/ksseono/Alfred.alfredpreferences/workflows/user.workflow.6543A76E-F5BF-4FB8-A158-DC8216A84E31/endic_naver_search.py", line 56, in main
    res_json = wf.cached_data("en_%s" % args, wrapper, max_age=600)
  File "/Users/ksseono/Alfred.alfredpreferences/workflows/user.workflow.6543A76E-F5BF-4FB8-A158-DC8216A84E31/workflow/workflow.py", line 2043, in cached_data
    data = data_func()
  File "/Users/ksseono/Alfred.alfredpreferences/workflows/user.workflow.6543A76E-F5BF-4FB8-A158-DC8216A84E31/endic_naver_search.py", line 54, in wrapper
    return get_dictionary_data(args)
  File "/Users/ksseono/Alfred.alfredpreferences/workflows/user.workflow.6543A76E-F5BF-4FB8-A158-DC8216A84E31/endic_naver_search.py", line 38, in get_dictionary_data
    r = web.get(url, params)
  File "/Users/ksseono/Alfred.alfredpreferences/workflows/user.workflow.6543A76E-F5BF-4FB8-A158-DC8216A84E31/workflow/web.py", line 593, in get
    return request('GET', url, params, headers=headers, cookies=cookies,
                   auth=auth, timeout=timeout, allow_redirects=allow_redirects,
                   stream=stream)
  File "/Users/ksseono/Alfred.alfredpreferences/workflows/user.workflow.6543A76E-F5BF-4FB8-A158-DC8216A84E31/workflow/web.py", line 583, in request
    return Response(req, stream)
  File "/Users/ksseono/Alfred.alfredpreferences/workflows/user.workflow.6543A76E-F5BF-4FB8-A158-DC8216A84E31/workflow/web.py", line 233, in __init__
    self.raw = urllib.request.urlopen(request, context=context)
               ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 489, in open
    response = self._open(req, data)
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 506, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
                              '_open', req)
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 1367, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        context=self._context)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1028)>
13:49:47 workflow.py:2524 DEBUG    ---------- finished in 0.035s ----------
[13:49:47.322] Naver Search[Script Filter] {
  "items": [
    {
      "title": "Error in workflow 'Naver Search'",
      "subtitle": "<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1028)>",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}
```

**Comment by ksseono** [comment]
지금 발견했는데, 테더링으로 했을땐 정상동작하는 것을 보니 회사 네트워크에서만 막히는 것 같기도 하네요..
