### ISSUE TITLE
안녕하세요 네이버맵 검색시 HTTP Error 403: Forbidden 메세지가 나오는데 혹시 원인을 알 수있을까요?

### ISSUE THREAD

**Issue by circumeo** [Kuniz/alfnaversearch#29]
안녕하세요 네이버맵 검색시 HTTP Error 403: Forbidden 메세지가 나오는데 혹시 원인을 알 수있을까요?

`[02:18:25.407] Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] Queuing argument 'ㄱ'
[02:18:25.420] Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] Queuing argument '가'
[02:18:25.456] Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] Queuing argument '강'
[02:18:25.598] Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] Script with argv '(null)' finished
[02:18:25.603] ERROR: Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] Code 1: .
02:18:25 workflow.py:2482 DEBUG    ---------- Naver (0.3.1) ----------
02:18:25 workflow.py:2037 DEBUG    loading cached data: /Users/greedist/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.jinukbaek.alfnaversearch/location_data.pickle
02:18:25 workflow.py:2502 ERROR    HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/workflow/workflow.py", line 2495, in run
    func(self)
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/naver_map.py", line 60, in main
    res_json = wf.cached_data(f"navmap_{args}", wrapper, max_age=30)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/workflow/workflow.py", line 2043, in cached_data
    data = data_func()
           ^^^^^^^^^^^
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/naver_map.py", line 58, in wrapper
    return get_data(args)
           ^^^^^^^^^^^^^^
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/naver_map.py", line 45, in get_data
    r.raise_for_status()
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/workflow/web.py", line 419, in raise_for_status
    raise self.error
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/workflow/web.py", line 228, in __init__
    self.raw = urllib.request.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
02:18:25 workflow.py:2524 DEBUG    ---------- finished in 0.046s ----------
[02:18:25.605] Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] {
  "items": [
    {
      "title": "Error in workflow 'Naver'",
      "subtitle": "HTTP Error 403: Forbidden",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}
[02:18:25.626] Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] Queuing argument '강ㅅ'
[02:18:25.716] Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] Queuing argument '강서'
[02:18:25.781] Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] Script with argv '(null)' finished
[02:18:25.787] ERROR: Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] Code 1: .
02:18:25 workflow.py:2482 DEBUG    ---------- Naver (0.3.1) ----------
02:18:25 workflow.py:2037 DEBUG    loading cached data: /Users/greedist/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.jinukbaek.alfnaversearch/location_data.pickle
02:18:25 workflow.py:2502 ERROR    HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/workflow/workflow.py", line 2495, in run
    func(self)
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/naver_map.py", line 60, in main
    res_json = wf.cached_data(f"navmap_{args}", wrapper, max_age=30)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/workflow/workflow.py", line 2043, in cached_data
    data = data_func()
           ^^^^^^^^^^^
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/naver_map.py", line 58, in wrapper
    return get_data(args)
           ^^^^^^^^^^^^^^
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/naver_map.py", line 45, in get_data
    r.raise_for_status()
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/workflow/web.py", line 419, in raise_for_status
    raise self.error
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/workflow/web.py", line 228, in __init__
    self.raw = urllib.request.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
02:18:25 workflow.py:2524 DEBUG    ---------- finished in 0.047s ----------
[02:18:25.789] Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] {
  "items": [
    {
      "title": "Error in workflow 'Naver'",
      "subtitle": "HTTP Error 403: Forbidden",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}
[02:18:25.808] Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] Queuing argument '강석'
[02:18:25.897] Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] Queuing argument '강서'
[02:18:25.904] Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] Queuing argument '강서구'
[02:18:25.958] Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] Script with argv '(null)' finished
[02:18:25.964] ERROR: Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] Code 1: .
02:18:25 workflow.py:2482 DEBUG    ---------- Naver (0.3.1) ----------
02:18:25 workflow.py:2037 DEBUG    loading cached data: /Users/greedist/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.jinukbaek.alfnaversearch/location_data.pickle
02:18:25 workflow.py:2502 ERROR    HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/workflow/workflow.py", line 2495, in run
    func(self)
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/naver_map.py", line 60, in main
    res_json = wf.cached_data(f"navmap_{args}", wrapper, max_age=30)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/workflow/workflow.py", line 2043, in cached_data
    data = data_func()
           ^^^^^^^^^^^
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/naver_map.py", line 58, in wrapper
    return get_data(args)
           ^^^^^^^^^^^^^^
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/naver_map.py", line 45, in get_data
    r.raise_for_status()
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/workflow/web.py", line 419, in raise_for_status
    raise self.error
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/workflow/web.py", line 228, in __init__
    self.raw = urllib.request.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
02:18:25 workflow.py:2524 DEBUG    ---------- finished in 0.049s ----------
[02:18:25.965] Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] {
  "items": [
    {
      "title": "Error in workflow 'Naver'",
      "subtitle": "HTTP Error 403: Forbidden",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}
[02:18:26.117] Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] Script with argv '(null)' finished
[02:18:26.125] ERROR: Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] Code 1: .
02:18:26 workflow.py:2482 DEBUG    ---------- Naver (0.3.1) ----------
02:18:26 workflow.py:2037 DEBUG    loading cached data: /Users/greedist/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.jinukbaek.alfnaversearch/location_data.pickle
02:18:26 workflow.py:2502 ERROR    HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/workflow/workflow.py", line 2495, in run
    func(self)
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/naver_map.py", line 60, in main
    res_json = wf.cached_data(f"navmap_{args}", wrapper, max_age=30)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/workflow/workflow.py", line 2043, in cached_data
    data = data_func()
           ^^^^^^^^^^^
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/naver_map.py", line 58, in wrapper
    return get_data(args)
           ^^^^^^^^^^^^^^
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/naver_map.py", line 45, in get_data
    r.raise_for_status()
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/workflow/web.py", line 419, in raise_for_status
    raise self.error
  File "/Users/greedist/Dropbox/Perosonal/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7020C616-7D76-4BE2-881F-57516E55E702/workflow/web.py", line 228, in __init__
    self.raw = urllib.request.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
02:18:26 workflow.py:2524 DEBUG    ---------- finished in 0.041s ----------
[02:18:26.127] Naver[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7020C616-7D76-4BE2-881F-57516E55E702%3E58425307-D5A4-469E-83F8-E75EAAB98FBF)] {
  "items": [
    {
      "title": "Error in workflow 'Naver'",
      "subtitle": "HTTP Error 403: Forbidden",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}`

**Comment by inchanS** [comment]
@circumeo 현재 이슈 관련하여 PR 넣었습니다. 
급하시다면 PR 내용중 변경사항을 먼저 적용하시면 문제없이 사용가능합니다. 
https://github.com/Kuniz/alfnaversearch/pull/30/files
workflow/naver_map.py파일의 변경내용만 보시면 돼요.

**Comment by circumeo** [comment]
> @circumeo 현재 이슈 관련하여 PR 넣었습니다. 급하시다면 PR 내용중 변경사항을 먼저 적용하시면 문제없이 사용가능합니다. https://github.com/Kuniz/alfnaversearch/pull/30/files workflow/naver_map.py파일의 변경내용만 보시면 돼요.

빠르게 피드백 주셔서 정말 감사합니다.
덕분에 항상 너무 감사하게 잘 사용하고 있습니다!

**Comment by Kuniz** [comment]
PR반영하여 Release 하였습니다. 감사합니다.
