### ISSUE TITLE
Error in workflow 'com.uturtle.alfnaversearch'

### ISSUE THREAD

**Issue by eungbean** [Kuniz/alfnaversearch#9]
logging
```
[15:07:36.692] Naver Search[Script Filter] Queuing argument 't'
[15:07:36.873] Naver Search[Script Filter] Script with argv '(null)' finished
[15:07:36.877] ERROR: Naver Search[Script Filter] Code 1: 15:07:36 workflow.py:2249 DEBUG    workflow version: 0.0.12
15:07:36 workflow.py:2267 ERROR    HTTP Error 503: Service Unavailable
Traceback (most recent call last):
  File "/Users/2flash/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.27AB676C-B1BF-4952-B776-F18B9334E3AC/workflow/workflow.py", line 2260, in run
    func(self)
  File "endic_naver_search.py", line 54, in main
    res_json = wf.cached_data("en_%s" % args, wrapper, max_age=600)
  File "/Users/2flash/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.27AB676C-B1BF-4952-B776-F18B9334E3AC/workflow/workflow.py", line 1890, in cached_data
    data = data_func()
  File "endic_naver_search.py", line 52, in wrapper
    return get_dictionary_data(args)
  File "endic_naver_search.py", line 37, in get_dictionary_data
    r.raise_for_status()
  File "/Users/2flash/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.27AB676C-B1BF-4952-B776-F18B9334E3AC/workflow/web.py", line 405, in raise_for_status
    raise self.error
HTTPError: HTTP Error 503: Service Unavailable
15:07:36 workflow.py:2290 DEBUG    workflow finished in 0.017 seconds
[15:07:36.879] Naver Search[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'com.uturtle.alfnaversearch'</title><subtitle>HTTP Error 503: Service Unavailable</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
```

**Comment by eungbean** [comment]
`endic_naver_search.py ` 의 line 25 수정사항이 반영이 안되었습니다.

**Comment by Kuniz** [comment]
https://github.com/Kuniz/alfnaversearch/releases/tag/v0.0.13

해당부분 PR보내주신 것 적용하여 릴리즈하였습니다! 감사합니다!
